sudo: required
dist: trusty
branches:
  only:
    # Only build on pushes or pull requests to master branch.
    - master
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  # To avoid matplotlib errors.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # Give xvfb some time to start.
  - sudo apt-get update -qq
  # Install scipy/numpy/pyqt dependencies.
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran qt5-default
  - pip install pytest-cov scipy
  # Download SIP and PyQt5 source, and build. In Python3, can use pip.
  - cd ..
  - curl -L -O https://sourceforge.net/projects/pyqt/files/sip/sip-4.19/sip-4.19.tar.gz
  - tar -xvf sip-4.19.tar.gz
  - cd sip-4.19
  - python configure.py
  - make -j 2
  - sudo make install
  - cd ..
  - curl -L -O https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.7.1/PyQt5_gpl-5.7.1.tar.gz
  - tar -xvf PyQt5_gpl-5.7.1.tar.gz
  - cd PyQt5_gpl-5.7.1
  - python configure.py --confirm-license
  - travis_wait make -j 2  # travis_wait times out at 20 min by default.
  - sudo make install
  - cd ../rteeg
  # Test install.
  - python -c 'from PyQt5 import QtCore, QtGui, QtWidgets'

install:
  # Install dependencies.
  - pip install -r requirements.txt
# Command to run tests.
script:
  - py.test --cov=./

after_success:
  # Run Code Coverage
  - bash <(curl -s https://codecov.io/bash)
