sudo: required
dist: trusty  # Ubuntu 14.04 LTS
branches:
  only:
    - master  # Only build on pushes or pull requests to master branch.
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  # To avoid matplotlib errors.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # Give xvfb some time to start.
  - sudo apt-get update -qq
  # Install scipy/numpy/pyqt dependencies.
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran qt5-default
  - pip install pytest-cov pytest-qt scipy
  - bash -e .build_pyqt5.sh
install:
  # Install dependencies.
  - pip install -r requirements.txt
script:
  - py.test --cov=./
after_success:
  # Run Code Coverage
  - bash <(curl -s https://codecov.io/bash)
