branches:
  only:
    # Only build on pushes or pull requests to master branch.
    - master
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo add-apt-repository ppa:canonical-qt5-edgers/ubuntu1204-qt5
  - sudo apt-get update
  - sudo apt-get qtbase-opensource-src
  # - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  # Install scipy/numpy dependencies.
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install pytest-cov scipy
  # Download SIP and PyQt5 source, and build. In Python3, can use pip.
  - cd ..
  - curl -L -O https://sourceforge.net/projects/pyqt/files/sip/sip-4.19/sip-4.19.tar.gz
  - tar -xvf sip-4.19.tar.gz
  - cd sip-4.19
  - python configure.py
  - make -j 2
  - sudo make install
  - cd ..
  - curl -L -O https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.7.1/PyQt5_gpl-5.7.1.tar.gz
  - tar -xvf PyQt5_gpl-5.7.1.tar.gz
  - cd PyQt5_gpl-5.7.1
  - python configure.py --confirm-license
  - travis_wait make -j 2  # travis_wait times out at 20 min by default.
  - sudo make install
  - cd ../rteeg
  # Test install.
  - python -c 'from PyQt5 import QtCore, QtGui, QtWidgets'

install:
  # Install dependencies.
  - pip install -r requirements.txt
# Command to run tests.
script:
  - py.test --cov=./

after_success:
  # Run Code Coverage
  - bash <(curl -s https://codecov.io/bash)
